(module
 (import "env" "readInt" (func $readInt (result i32)))
 (import "env" "readDouble" (func $readDouble (result f64)))
 (import "env" "printInt" (func $printInt (param i32)))
 (import "env" "printDouble" (func $printDouble (param f64)))
 (func
  $main
  (result i32)
  (local $ix$0 i32)
  (local $ix$2 i32)
  (local $ii$1 i32)
  (local $ix$3 i32)
  (local $ix$1 i32)
  (i32.const 0)
  (local.set $ix$0)
  (i32.const 1)
  (if (then (i32.const 1) (local.set $ix$2)) (else))
  (local.get $ix$0)
  (call $printInt)
  (i32.const 1)
  (if (then (i32.const 2) (local.set $ix$2)) (else))
  (local.get $ix$0)
  (call $printInt)
  (i32.const 0)
  (if (then) (else (i32.const 3) (local.set $ix$2)))
  (local.get $ix$0)
  (call $printInt)
  (i32.const 0)
  (if (then) (else (i32.const 4) (local.set $ix$2)))
  (local.get $ix$0)
  (call $printInt)
  (i32.const 0)
  (local.set $ii$1)
  (block
   (loop
    (local.get $ii$1)
    (local.get $ii$1)
    (i32.const 1)
    i32.add
    (local.set $ii$1)
    (i32.const 1)
    i32.lt_s
    i32.eqz
    (br_if 1)
    (i32.const 5)
    (local.set $ix$3)
    (br 0)
   )
  )
  (local.get $ix$0)
  (call $printInt)
  (i32.const 0)
  (local.set $ii$1)
  (block
   (loop
    (local.get $ii$1)
    (local.get $ii$1)
    (i32.const 1)
    i32.add
    (local.set $ii$1)
    (i32.const 1)
    i32.lt_s
    i32.eqz
    (br_if 1)
    (i32.const 6)
    (local.set $ix$3)
    (br 0)
   )
  )
  (local.get $ix$0)
  (call $printInt)
  (i32.const 7)
  (local.set $ix$1)
  (local.get $ix$0)
  (call $printInt)
  (i32.const 8)
  (local.set $ix$1)
  (local.get $ix$0)
  (call $printInt)
  (i32.const 0)
  return
 )
 (export "main" (func $main))
)